openapi: 3.0.3
info:
  title: Swagger Product Service
  version: 1.0.0
servers:
  - url: https://npfagdphr1.execute-api.us-east-1.amazonaws.com/prod
tags:
  - name: products
    description: Get products from Product Service Database
paths:
  /products:
    get:
      tags:
        - products
      summary: Get list of products
      operationId: getProductsList
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '502':
          description: Server error
  
  /products/{productId}:
    get:
      tags:
        - products
      summary: Return product by ID
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type : integer
            format: int64
      operationId: getProductsbyId
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
        '500':
          description: Invalid product id
        '502':
          description: Server error
          
  /products/create:
    post:
      tags:
        - products
      summary: Create product
      operationId: createProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostProduct'
      responses:
        '200':
          description: Successful operation
        '404':
          description: Product not found
        '500':
          description: Invalid product id
        '502':
          description: Server error

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
          maximum: 1000
        title:
          type: string
        description:
          type: string
        price:
          type: number
          format: double
        count:
          type: integer
          format: int64
    PostProduct:
      type: object
      properties:
        title:
          type: string
          example: 'Product Title'
        description:
          type: string
          example: 'Product Description'
        price:
          type: number
          format: double